apiVersion: v1
kind: Service
metadata:
  name: xem-core
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: xem-port
      port: 7890
      targetPort: 7890
      protocol: TCP
  selector:
    service: xem-core
